import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import ApolloWrapper from "./ApolloWrapper";
import DataLoader from "@/components/admin/products/LoadAllData";
import ClientOnlyWrapper from "@/components/ClientOnlyWrapper";
import ToasterProvider from "@/components/ToasterProvider";

export const metadata: Metadata = {
  title: "POS SYSTEM",
  description: "Generated by BSIS 32A1",
  icons: {
    icon: "/icon/pos-icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="!bg-bgWhite min-h-screen w-full mx-auto max-w-[1280px]">
        <ApolloWrapper>
          <NavbarWrapper />

          <ClientOnlyWrapper>
            <ToasterProvider />
          </ClientOnlyWrapper>

          <main className="relative overflow-hidden">{children}</main>
          <DataLoader />
        </ApolloWrapper>
      </body>
    </html>
  );
}
