import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import { ApolloProvider } from '@apollo/client';
import client from "./lib/apolloClient"; 

export const metadata: Metadata = {
  title: "POS SYSTEM",
  description: "Generated by BSIS 32A1",
  icons: {
    icon: "/icon/pos-icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="!bg-bgWhite min-h-screen w-full mx-auto max-w-[1280px]">
        <ApolloProvider client={client}>
          <NavbarWrapper />
          <main className="relative overflow-hidden">{children}</main>
        </ApolloProvider>
      </body>
    </html>
  );
}
