import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import ApolloWrapper from "./ApolloWrapper";
import DataLoader from "@/components/admin/products/LoadAllData";
import ClientOnlyWrapper from "@/components/ClientOnlyWrapper";
import ToasterProvider from "@/components/ToasterProvider";

export const metadata: Metadata = {
  title: "POS SYSTEM",
  description: "Generated by BSIS 32A1",
  icons: {
    icon: "/icon/pos-icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className="!bg-bgWhite min-h-screen w-full mx-auto max-w-[1280px]"> */}
      <body className="!bg-bgWhite w-full mx-auto max-w-[1280px] max-h-screen overflow-y-auto">
        <ApolloWrapper>
          <NavbarWrapper />

          <ClientOnlyWrapper>
            <ToasterProvider />
          </ClientOnlyWrapper>

          {/* <main className="relative overflow-hidden">{children}</main> */}
          <main className="relative overflow-y-auto max-h-screen hide-scrollbar">
            {children}
          </main>

          <DataLoader />
        </ApolloWrapper>
      </body>
    </html>
  );
}
